version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal" ]
    working_dir: /home/dynamodblocal
    volumes:
      - dynamodb_data:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - AWS_REGION=us-east-1

  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  dynamodb_data:
  redis_data: